apiVersion: v2
name: cnpg-ui
description: Web UI for CloudNativePG management
version: 0.2.6
appVersion: "0.2.6"

dependencies:
  - name: cloudnative-pg
    version: "0.23.0"
    repository: https://cloudnative-pg.github.io/charts
    condition: cnpgOperator.enabled
